# Generated by Django 5.0.7 on 2026-08-04 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_key', models.CharField(editable=False, max_length=5, unique=True)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('reason_for_inspection', models.CharField(blank=True, default='', max_length=255)),
                ('inspector', models.CharField(blank=True, default='', max_length=255)),
                ('date_of_inspection', models.CharField(blank=True, default='', max_length=50)),
                ('summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImagePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('layout', models.CharField(choices=[('single', '1 Image Page'), ('double', '2 Image Page')], default='single', max_length=10)),
                ('issue_concern', models.TextField(blank=True, default='')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='inspections.inspectionform')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveIntegerField(default=1)),
                ('original_image', models.ImageField(blank=True, null=True, upload_to='uploads/originals/')),
                ('rendered_image', models.ImageField(blank=True, null=True, upload_to='uploads/rendered/')),
                ('crop_data', models.JSONField(blank=True, null=True)),
                ('shapes', models.JSONField(blank=True, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inspections.imagepage')),
            ],
            options={
                'ordering': ['slot'],
            },
        ),
    ]
