# Generated by Django 4.2.30 on 2026-08-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepage',
            name='layout',
            field=models.CharField(choices=[('main', 'Main Photo Page'), ('single', '1 Image Page'), ('double', '2 Image Page')], default='single', max_length=10),
        ),
    ]
