# Generated by Django 4.2.30 on 2026-08-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_alter_imagepage_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepage',
            name='photo_height_in',
            field=models.FloatField(default=5.6),
        ),
    ]
