# Generated by Django 4.2.30 on 2026-08-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_imagepage_photo_height_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepage',
            name='photo_width_in',
            field=models.FloatField(default=7.06),
        ),
    ]
